### PR TITLE
Fix splitting cluster on Rolling Update

### LINKED ISSUE #75: KUBE_PING warning with StatefulSet
The [WildFly Operator](/wildfly/wildlfy-operator) is using a `StatefulSet` to deploy application on Kubernetes/OpenShift.

It was possible to use KUBE_PING with WildFly 17 (and the JGroups version that it integrated) but there is a new warning with WildFly 18 during the deployment of the application:

```
08:46:20,187 WARN  [org.jgroups.protocols.kubernetes.KUBE_PING] (thread-17,ejb,clusterbench-1) metadata.labels.pod-template-hash not found in pod json. Impossible to reliably determine pod group during Rolling Update
```

Indeed pod-template-hash label is set only for pods coming from a `Deployment`[1] and is not present when a `StatefulSet` is used.

Is this warning by design or should KUBE_PING work with StatefulSets without any issue?

[1] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template-hash-label

### LINKED ISSUE #77: Initial discovery ends up in singleton partitions
When performing initial discovery, all members end up in a singleton partition and then we merge them. This behavior might be dangerous and may lead to losing data. Here's an example:

```
FINE: jgroups-kube-ping-bcd595949-vr6tw-42848: installing view [jgroups-kube-ping-bcd595949-vr6tw-42848|0] (1) [jgroups-kube-ping-bcd595949-vr6tw-42848]
...
FINE: jgroups-kube-ping-bcd595949-vr6tw-42848: installing view [jgroups-kube-ping-bcd595949-vr6tw-42848|1] (2) [jgroups-kube-ping-bcd595949-vr6tw-42848, jgroups-kube-ping-bcd595949-7w9mc-57543]
```

### PR DESCRIPTION
**Pull request by slaskawi**
This Pull Request fixes warning message described in #75. It makes sure, all pods use correct group only if `split_clusters_during_rolling_update` is turned on. This warning needs to stay and shouldn't be silenced out. 

Additionally, this should work fine also with StatefulSets now.

The final change is for `KUBERNETES_SPLIT_CLUSTERS_DURING_ROLLING_UPDATE` functionality. Starting from now, the `KUBE_PING` will also take not ready Pods into consideration. By default, this option is set to `true`.

fixes #75
fixes #77

### CODE REVIEW

**Comment by slaskawi** [comment]
A working demo has been pushed into this repository: https://github.com/slaskawi/jgroups-kube-ping-bcd595949-vr6tw

File: src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java [hunk 1]
```diff
@@ -105,9 +105,12 @@
 
     @Property(description="The standard behavior during Rolling Update is to put all Pods in the same cluster. In" +
           " cases (application level incompatibility) this causes problems. One might decide to split clusters to" +
-          " 'old' and 'new' during that process")
+          " 'old' and 'new' during that process", systemProperty="KUBERNETES_SPLIT_CLUSTERS_DURING_ROLLING_UPDATE")
     protected boolean split_clusters_during_rolling_update;
 
+    @Property(description="Introduces similar behaviour to Kubernetes Services (using DNS) with publishNotReadyAddresses set to true." +
```
Comment (rhusar) [inline src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java]: Missing space after '...set to true.'

File: src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java [hunk 2]
```diff
@@ -243,7 +246,11 @@ public void findMembers(List<Address> members, boolean initial_discovery, Respon
             if(physical_addr != null) {
                 String senderIp = ((IpAddress)physical_addr).getIpAddress().getHostAddress();
                 // Please note we search for sender parent group through all pods, ever not ready. It's because JGroup discovery is performed
-                // before Wildfly can respond to http liveness probe.
+                // before Wildfly can respond to http readiness probe.
```
Comment (rhusar) [inline src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java]: s/Wildfly/WildFly

Comment (slaskawi) [reply src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java]: Fixed

File: src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java (hunk 1 above)
Comment (slaskawi) [reply src/main/java/org/jgroups/protocols/kubernetes/KUBE_PING.java]: Fixed.
